### PR TITLE
fix: Replace internal Structs class with google-cloud-core version

### LINKED ISSUE #1492: Replace internal Structs class with google-cloud-core version
Just merged in https://github.com/googleapis/sdk-platform-java/pull/2278, once it is released we should swap out any usages of https://github.com/googleapis/java-logging/blob/main/google-cloud-logging/src/main/java/com/google/cloud/logging/Structs.java with this upstream version instead.

### PR DESCRIPTION
**Pull request by cindy-peng**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/java-logging/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

Fixes #1492  ☕️

The new common structs mapper utility in google cloud core including  has been released yesterday in 3.21.0: 
https://github.com/googleapis/sdk-platform-java/pull/2290
https://github.com/googleapis/sdk-platform-java/pull/2278

This is to replace the internal structs usage with the upstream version.

### CODE REVIEW

**Review by gkevinzheng — APPROVED** [review]

File: google-cloud-logging/src/main/java/com/google/cloud/logging/Structs.java [hunk 1]
```diff
@@ -1,150 +0,0 @@
...
-import java.util.AbstractSet;
-import java.util.Iterator;
-import java.util.Map;
-import java.util.Set;
-
-/**
- * This class contains static utility methods that operate on or return protobuf's {@code Struct}
- * objects.
- */
-final class Structs {
```
Comment (daniel-sanche) [inline google-cloud-logging/src/main/java/com/google/cloud/logging/Structs.java:40]: Just to be sure: this isn't public since it's missing the `public` modifier, right?

**Review by daniel-sanche — APPROVED** [review]
LGTM, assuming no public API changes
