### PR TITLE
fix: Fix some typos

### LINKED ISSUE #1007: Various typos in the code
Our source code analyzer found various trivial typos in the code (none in interfaces, just internal stuff).

Will send a PR

### PR DESCRIPTION
**Pull request by bpcreech**
Fixes #1007

### CODE REVIEW

**Review by losalex — APPROVED** [review]
LGTM - thanks!

File: google-cloud-logging/src/main/java/com/google/cloud/logging/Instrumentation.java [hunk 1]
```diff
@@ -114,7 +114,7 @@ public static WriteOption[] addPartialSuccessOption(WriteOption[] options) {
    *     with 'java'. Will be truncated if longer than 14 characters.
    * @param libraryVersion {string} The version of the logging library to be reported. Will be
    *     truncated if longer than 14 characters.
-   * @returns {LogEntry} The entry with diagnostic instrumentation data.
+   * @return {LogEntry} The entry with diagnostic instrumentation data.
```
Comment (losalex) [inline google-cloud-logging/src/main/java/com/google/cloud/logging/Instrumentation.java:117]: I think lint test fails on this file and I guess it is related to a comment you changed

Comment (bpcreech) [reply google-cloud-logging/src/main/java/com/google/cloud/logging/Instrumentation.java:117]: oops, fixed
